global using System;
global using System;
global using System.Diagnostics.CodeAnalysis;
global using System.IO;
global using System.Text;
global using Avalonia;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;